/**
 * Cidades atendidas — gerado a partir de
 * `../Apresentação/Cidades_atendidas_Sao_Paulo_e_Goiania - Excel.xlsx` (planilha da Sólida, 10/09/2026).
 * UF inferida pela posição na planilha (GO/DF partindo de SP; RJ/SP partindo de Goiânia).
 * Para atualizar: edite a planilha e rode o script em `../Apresentação/gerar-cidades.py`.
 */

export type CityOrigin = "sao-paulo" | "goiania";
export type CityUf = "GO" | "DF" | "SP" | "RJ";

export type ServedCity = { name: string; uf: CityUf; origin: CityOrigin };

export const CITY_ORIGINS: { id: CityOrigin; label: string; short: string; unit: string }[] = [
  { id: "sao-paulo", label: "Partindo de São Paulo", short: "São Paulo", unit: "Filial Guarulhos-SP" },
  { id: "goiania", label: "Partindo de Goiânia", short: "Goiânia", unit: "Matriz Goiânia-GO" },
];

export const UF_LABELS: Record<CityUf, string> = {
  GO: "Goiás",
  DF: "Distrito Federal",
  SP: "São Paulo",
  RJ: "Rio de Janeiro",
};

export const SERVED_CITIES: ServedCity[] = [
  { name: "Abadia de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Abadiânia", uf: "GO", origin: "sao-paulo" },
  { name: "Acreúna", uf: "GO", origin: "sao-paulo" },
  { name: "Adelândia", uf: "GO", origin: "sao-paulo" },
  { name: "Água Fria de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Água Limpa", uf: "GO", origin: "sao-paulo" },
  { name: "Águas Lindas de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Alexânia", uf: "GO", origin: "sao-paulo" },
  { name: "Aloândia", uf: "GO", origin: "sao-paulo" },
  { name: "Alto Horizonte", uf: "GO", origin: "sao-paulo" },
  { name: "Alto Paraíso de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Alvorada do Norte", uf: "GO", origin: "sao-paulo" },
  { name: "Amaralina", uf: "GO", origin: "sao-paulo" },
  { name: "Americano do Brasil", uf: "GO", origin: "sao-paulo" },
  { name: "Amorinópolis", uf: "GO", origin: "sao-paulo" },
  { name: "Anápolis", uf: "GO", origin: "sao-paulo" },
  { name: "Anhanguera", uf: "GO", origin: "sao-paulo" },
  { name: "Anicuns", uf: "GO", origin: "sao-paulo" },
  { name: "Aparecida de Goiânia", uf: "GO", origin: "sao-paulo" },
  { name: "Aparecida do Rio Doce", uf: "GO", origin: "sao-paulo" },
  { name: "Aporé", uf: "GO", origin: "sao-paulo" },
  { name: "Araçu", uf: "GO", origin: "sao-paulo" },
  { name: "Aragarças", uf: "GO", origin: "sao-paulo" },
  { name: "Aragoiânia", uf: "GO", origin: "sao-paulo" },
  { name: "Araguapaz", uf: "GO", origin: "sao-paulo" },
  { name: "Arenópolis", uf: "GO", origin: "sao-paulo" },
  { name: "Aruanã", uf: "GO", origin: "sao-paulo" },
  { name: "Aurilândia", uf: "GO", origin: "sao-paulo" },
  { name: "Avelinópolis", uf: "GO", origin: "sao-paulo" },
  { name: "Baliza", uf: "GO", origin: "sao-paulo" },
  { name: "Barro Alto", uf: "GO", origin: "sao-paulo" },
  { name: "Bela Vista de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Bom Jardim de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Bom Jesus", uf: "GO", origin: "sao-paulo" },
  { name: "Bonfinópolis", uf: "GO", origin: "sao-paulo" },
  { name: "Bonópolis", uf: "GO", origin: "sao-paulo" },
  { name: "Brazabrantes", uf: "GO", origin: "sao-paulo" },
  { name: "Britânia", uf: "GO", origin: "sao-paulo" },
  { name: "Buriti Alegre", uf: "GO", origin: "sao-paulo" },
  { name: "Buriti de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Buritinópolis", uf: "GO", origin: "sao-paulo" },
  { name: "Cabeceiras", uf: "GO", origin: "sao-paulo" },
  { name: "Cachoeira Alta", uf: "GO", origin: "sao-paulo" },
  { name: "Cachoeira de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Cachoeira Dourada", uf: "GO", origin: "sao-paulo" },
  { name: "Caçu", uf: "GO", origin: "sao-paulo" },
  { name: "Caiapônia", uf: "GO", origin: "sao-paulo" },
  { name: "Calcilândia", uf: "GO", origin: "sao-paulo" },
  { name: "Caldas Novas", uf: "GO", origin: "sao-paulo" },
  { name: "Caldazinha", uf: "GO", origin: "sao-paulo" },
  { name: "Campestre de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Campinaçu", uf: "GO", origin: "sao-paulo" },
  { name: "Campinorte", uf: "GO", origin: "sao-paulo" },
  { name: "Campo Alegre de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Campo Limpo de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Campos Belos", uf: "GO", origin: "sao-paulo" },
  { name: "Campos Verdes", uf: "GO", origin: "sao-paulo" },
  { name: "Carmo do Rio Verde", uf: "GO", origin: "sao-paulo" },
  { name: "Castelândia", uf: "GO", origin: "sao-paulo" },
  { name: "Catalão", uf: "GO", origin: "sao-paulo" },
  { name: "Caturaí", uf: "GO", origin: "sao-paulo" },
  { name: "Cavalcante", uf: "GO", origin: "sao-paulo" },
  { name: "Ceres", uf: "GO", origin: "sao-paulo" },
  { name: "Cezarina", uf: "GO", origin: "sao-paulo" },
  { name: "Chapadão do Céu", uf: "GO", origin: "sao-paulo" },
  { name: "Cidade Ocidental", uf: "GO", origin: "sao-paulo" },
  { name: "Cocalzinho de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Colinas do Sul", uf: "GO", origin: "sao-paulo" },
  { name: "Córrego do Ouro", uf: "GO", origin: "sao-paulo" },
  { name: "Corumbá de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Corumbaíba", uf: "GO", origin: "sao-paulo" },
  { name: "Cristalina", uf: "GO", origin: "sao-paulo" },
  { name: "Cristianópolis", uf: "GO", origin: "sao-paulo" },
  { name: "Crixás", uf: "GO", origin: "sao-paulo" },
  { name: "Cromínia", uf: "GO", origin: "sao-paulo" },
  { name: "Cumari", uf: "GO", origin: "sao-paulo" },
  { name: "Damianópolis", uf: "GO", origin: "sao-paulo" },
  { name: "Damolândia", uf: "GO", origin: "sao-paulo" },
  { name: "Davinópolis", uf: "GO", origin: "sao-paulo" },
  { name: "Diorama", uf: "GO", origin: "sao-paulo" },
  { name: "Divinópolis de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Doverlândia", uf: "GO", origin: "sao-paulo" },
  { name: "Edéia", uf: "GO", origin: "sao-paulo" },
  { name: "Estrela do Norte", uf: "GO", origin: "sao-paulo" },
  { name: "Faina", uf: "GO", origin: "sao-paulo" },
  { name: "Fazenda Nova", uf: "GO", origin: "sao-paulo" },
  { name: "Firminópolis", uf: "GO", origin: "sao-paulo" },
  { name: "Flores de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Formosa", uf: "GO", origin: "sao-paulo" },
  { name: "Formoso", uf: "GO", origin: "sao-paulo" },
  { name: "Gameleira de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Goianápolis", uf: "GO", origin: "sao-paulo" },
  { name: "Goiandira", uf: "GO", origin: "sao-paulo" },
  { name: "Goianésia", uf: "GO", origin: "sao-paulo" },
  { name: "Goiânia", uf: "GO", origin: "sao-paulo" },
  { name: "Goianira", uf: "GO", origin: "sao-paulo" },
  { name: "Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Goiatuba", uf: "GO", origin: "sao-paulo" },
  { name: "Gouvelândia", uf: "GO", origin: "sao-paulo" },
  { name: "Guapó", uf: "GO", origin: "sao-paulo" },
  { name: "Guaraíta", uf: "GO", origin: "sao-paulo" },
  { name: "Guarani de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Guarinos", uf: "GO", origin: "sao-paulo" },
  { name: "Heitoraí", uf: "GO", origin: "sao-paulo" },
  { name: "Hidrolândia", uf: "GO", origin: "sao-paulo" },
  { name: "Hidrolina", uf: "GO", origin: "sao-paulo" },
  { name: "Iaciara", uf: "GO", origin: "sao-paulo" },
  { name: "Inaciolândia", uf: "GO", origin: "sao-paulo" },
  { name: "Indiara", uf: "GO", origin: "sao-paulo" },
  { name: "Inhumas", uf: "GO", origin: "sao-paulo" },
  { name: "Ipameri", uf: "GO", origin: "sao-paulo" },
  { name: "Ipiranga de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Iporá", uf: "GO", origin: "sao-paulo" },
  { name: "Israelândia", uf: "GO", origin: "sao-paulo" },
  { name: "Itaberaí", uf: "GO", origin: "sao-paulo" },
  { name: "Itaguari", uf: "GO", origin: "sao-paulo" },
  { name: "Itaguaru", uf: "GO", origin: "sao-paulo" },
  { name: "Itajá", uf: "GO", origin: "sao-paulo" },
  { name: "Itapaci", uf: "GO", origin: "sao-paulo" },
  { name: "Itapirapuã", uf: "GO", origin: "sao-paulo" },
  { name: "Itapuranga", uf: "GO", origin: "sao-paulo" },
  { name: "Itarumã", uf: "GO", origin: "sao-paulo" },
  { name: "Itauçu", uf: "GO", origin: "sao-paulo" },
  { name: "Itumbiara", uf: "GO", origin: "sao-paulo" },
  { name: "Ivolândia", uf: "GO", origin: "sao-paulo" },
  { name: "Jandaia", uf: "GO", origin: "sao-paulo" },
  { name: "Jaraguá", uf: "GO", origin: "sao-paulo" },
  { name: "Jataí", uf: "GO", origin: "sao-paulo" },
  { name: "Jaupaci", uf: "GO", origin: "sao-paulo" },
  { name: "Jesúpolis", uf: "GO", origin: "sao-paulo" },
  { name: "Joviânia", uf: "GO", origin: "sao-paulo" },
  { name: "Jussara", uf: "GO", origin: "sao-paulo" },
  { name: "Lagoa Santa", uf: "GO", origin: "sao-paulo" },
  { name: "Leopoldo de Bulhões", uf: "GO", origin: "sao-paulo" },
  { name: "Luziânia", uf: "GO", origin: "sao-paulo" },
  { name: "Mairipotaba", uf: "GO", origin: "sao-paulo" },
  { name: "Mambaí", uf: "GO", origin: "sao-paulo" },
  { name: "Mara Rosa", uf: "GO", origin: "sao-paulo" },
  { name: "Marzagão", uf: "GO", origin: "sao-paulo" },
  { name: "Matrinchã", uf: "GO", origin: "sao-paulo" },
  { name: "Maurilândia", uf: "GO", origin: "sao-paulo" },
  { name: "Mimoso de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Minaçu", uf: "GO", origin: "sao-paulo" },
  { name: "Mineiros", uf: "GO", origin: "sao-paulo" },
  { name: "Moiporá", uf: "GO", origin: "sao-paulo" },
  { name: "Monte Alegre de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Montes Claros de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Montividiu", uf: "GO", origin: "sao-paulo" },
  { name: "Montividiu do Norte", uf: "GO", origin: "sao-paulo" },
  { name: "Morrinhos", uf: "GO", origin: "sao-paulo" },
  { name: "Morro Agudo de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Mossâmedes", uf: "GO", origin: "sao-paulo" },
  { name: "Mozarlândia", uf: "GO", origin: "sao-paulo" },
  { name: "Mundo Novo", uf: "GO", origin: "sao-paulo" },
  { name: "Mutunópolis", uf: "GO", origin: "sao-paulo" },
  { name: "Nazário", uf: "GO", origin: "sao-paulo" },
  { name: "Nerópolis", uf: "GO", origin: "sao-paulo" },
  { name: "Niquelândia", uf: "GO", origin: "sao-paulo" },
  { name: "Nova América", uf: "GO", origin: "sao-paulo" },
  { name: "Nova Aurora", uf: "GO", origin: "sao-paulo" },
  { name: "Nova Crixás", uf: "GO", origin: "sao-paulo" },
  { name: "Nova Glória", uf: "GO", origin: "sao-paulo" },
  { name: "Nova Iguaçu de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Nova Roma", uf: "GO", origin: "sao-paulo" },
  { name: "Nova Veneza", uf: "GO", origin: "sao-paulo" },
  { name: "Novo Brasil", uf: "GO", origin: "sao-paulo" },
  { name: "Novo Gama", uf: "GO", origin: "sao-paulo" },
  { name: "Novo Planalto", uf: "GO", origin: "sao-paulo" },
  { name: "Orizona", uf: "GO", origin: "sao-paulo" },
  { name: "Ouro Verde de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Ouvidor", uf: "GO", origin: "sao-paulo" },
  { name: "Padre Bernardo", uf: "GO", origin: "sao-paulo" },
  { name: "Palestina de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Palmeiras de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Palmelo", uf: "GO", origin: "sao-paulo" },
  { name: "Palminópolis", uf: "GO", origin: "sao-paulo" },
  { name: "Panamá", uf: "GO", origin: "sao-paulo" },
  { name: "Paranaiguara", uf: "GO", origin: "sao-paulo" },
  { name: "Paraúna", uf: "GO", origin: "sao-paulo" },
  { name: "Perolândia", uf: "GO", origin: "sao-paulo" },
  { name: "Petrolina de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Pilar de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Piracanjuba", uf: "GO", origin: "sao-paulo" },
  { name: "Piranhas", uf: "GO", origin: "sao-paulo" },
  { name: "Pirenópolis", uf: "GO", origin: "sao-paulo" },
  { name: "Pires do Rio", uf: "GO", origin: "sao-paulo" },
  { name: "Planaltina", uf: "GO", origin: "sao-paulo" },
  { name: "Pontalina", uf: "GO", origin: "sao-paulo" },
  { name: "Porangatu", uf: "GO", origin: "sao-paulo" },
  { name: "Porteirão", uf: "GO", origin: "sao-paulo" },
  { name: "Portelândia", uf: "GO", origin: "sao-paulo" },
  { name: "Posse", uf: "GO", origin: "sao-paulo" },
  { name: "Professor Jamil", uf: "GO", origin: "sao-paulo" },
  { name: "Quirinópolis", uf: "GO", origin: "sao-paulo" },
  { name: "Rialma", uf: "GO", origin: "sao-paulo" },
  { name: "Rianápolis", uf: "GO", origin: "sao-paulo" },
  { name: "Rio Quente", uf: "GO", origin: "sao-paulo" },
  { name: "Rio Verde", uf: "GO", origin: "sao-paulo" },
  { name: "Rubiataba", uf: "GO", origin: "sao-paulo" },
  { name: "Sanclerlândia", uf: "GO", origin: "sao-paulo" },
  { name: "Santa Bárbara de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Santa Cruz de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Santa Fé de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Santa Helena de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Santa Isabel", uf: "GO", origin: "sao-paulo" },
  { name: "Santa Rita do Araguaia", uf: "GO", origin: "sao-paulo" },
  { name: "Santa Rita do Novo Destino", uf: "GO", origin: "sao-paulo" },
  { name: "Santa Rosa de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Santa Tereza de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Santa Terezinha de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Santo Antônio da Barra", uf: "GO", origin: "sao-paulo" },
  { name: "Santo Antônio de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Santo Antônio do Descoberto", uf: "GO", origin: "sao-paulo" },
  { name: "São Domingos", uf: "GO", origin: "sao-paulo" },
  { name: "São Francisco de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "São Gabriel de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "São João d'Aliança", uf: "GO", origin: "sao-paulo" },
  { name: "São João da Paraúna", uf: "GO", origin: "sao-paulo" },
  { name: "São Luís de Montes Belos", uf: "GO", origin: "sao-paulo" },
  { name: "São Luiz do Norte", uf: "GO", origin: "sao-paulo" },
  { name: "São Miguel do Araguaia", uf: "GO", origin: "sao-paulo" },
  { name: "São Miguel do Passa Quatro", uf: "GO", origin: "sao-paulo" },
  { name: "São Patrício", uf: "GO", origin: "sao-paulo" },
  { name: "São Simão", uf: "GO", origin: "sao-paulo" },
  { name: "Senador Canedo", uf: "GO", origin: "sao-paulo" },
  { name: "Serranópolis", uf: "GO", origin: "sao-paulo" },
  { name: "Silvânia", uf: "GO", origin: "sao-paulo" },
  { name: "Simolândia", uf: "GO", origin: "sao-paulo" },
  { name: "Sítio d'Abadia", uf: "GO", origin: "sao-paulo" },
  { name: "Souzalândia", uf: "GO", origin: "sao-paulo" },
  { name: "Taquaral de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Teresina de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Terezópolis de Goiás", uf: "GO", origin: "sao-paulo" },
  { name: "Três Ranchos", uf: "GO", origin: "sao-paulo" },
  { name: "Trindade", uf: "GO", origin: "sao-paulo" },
  { name: "Turvânia", uf: "GO", origin: "sao-paulo" },
  { name: "Turvelândia", uf: "GO", origin: "sao-paulo" },
  { name: "Uirapuru", uf: "GO", origin: "sao-paulo" },
  { name: "Uruaçu", uf: "GO", origin: "sao-paulo" },
  { name: "Uruana", uf: "GO", origin: "sao-paulo" },
  { name: "Vila Propício", uf: "GO", origin: "sao-paulo" },
  { name: "Brasília", uf: "DF", origin: "sao-paulo" },
  { name: "Brasília (Ceilândia)", uf: "DF", origin: "sao-paulo" },
  { name: "Brasília (Cruzeiro)", uf: "DF", origin: "sao-paulo" },
  { name: "Brasília (Guará)", uf: "DF", origin: "sao-paulo" },
  { name: "Brasília (Taguatinga)", uf: "DF", origin: "sao-paulo" },
  { name: "Candangolândia", uf: "DF", origin: "sao-paulo" },
  { name: "Gama", uf: "DF", origin: "sao-paulo" },
  { name: "Lago Norte e Lago Sul", uf: "DF", origin: "sao-paulo" },
  { name: "Núcleo Bandeirante", uf: "DF", origin: "sao-paulo" },
  { name: "Paranoá", uf: "DF", origin: "sao-paulo" },
  { name: "Planaltina", uf: "DF", origin: "sao-paulo" },
  { name: "Riacho Fundo", uf: "DF", origin: "sao-paulo" },
  { name: "Samambaia", uf: "DF", origin: "sao-paulo" },
  { name: "São Sebastião", uf: "DF", origin: "sao-paulo" },
  { name: "Sobradinho", uf: "DF", origin: "sao-paulo" },
  { name: "Belford Roxo", uf: "RJ", origin: "goiania" },
  { name: "Duque de Caxias", uf: "RJ", origin: "goiania" },
  { name: "Mesquita", uf: "RJ", origin: "goiania" },
  { name: "Nilópolis", uf: "RJ", origin: "goiania" },
  { name: "Niterói", uf: "RJ", origin: "goiania" },
  { name: "Nova Iguaçu", uf: "RJ", origin: "goiania" },
  { name: "Rio de Janeiro", uf: "RJ", origin: "goiania" },
  { name: "São Gonçalo", uf: "RJ", origin: "goiania" },
  { name: "São João de Meriti", uf: "RJ", origin: "goiania" },
  { name: "Alumínio", uf: "SP", origin: "goiania" },
  { name: "Americana", uf: "SP", origin: "goiania" },
  { name: "Amparo", uf: "SP", origin: "goiania" },
  { name: "Angatuba", uf: "SP", origin: "goiania" },
  { name: "Aparecida", uf: "SP", origin: "goiania" },
  { name: "Araçariguama", uf: "SP", origin: "goiania" },
  { name: "Araçoiaba da Serra", uf: "SP", origin: "goiania" },
  { name: "Areias", uf: "SP", origin: "goiania" },
  { name: "Arujá", uf: "SP", origin: "goiania" },
  { name: "Atibaia", uf: "SP", origin: "goiania" },
  { name: "Barueri", uf: "SP", origin: "goiania" },
  { name: "Biritiba-Mirim", uf: "SP", origin: "goiania" },
  { name: "Boituva", uf: "SP", origin: "goiania" },
  { name: "Cabreúva", uf: "SP", origin: "goiania" },
  { name: "Cajamar", uf: "SP", origin: "goiania" },
  { name: "Cajuru", uf: "SP", origin: "goiania" },
  { name: "Campinas", uf: "SP", origin: "goiania" },
  { name: "Campo Limpo Paulista", uf: "SP", origin: "goiania" },
  { name: "Campos do Jordão", uf: "SP", origin: "goiania" },
  { name: "Canas", uf: "SP", origin: "goiania" },
  { name: "Capivari", uf: "SP", origin: "goiania" },
  { name: "Carapicuíba", uf: "SP", origin: "goiania" },
  { name: "Cerquilho", uf: "SP", origin: "goiania" },
  { name: "Cesário Lange", uf: "SP", origin: "goiania" },
  { name: "Cotia", uf: "SP", origin: "goiania" },
  { name: "Cravinhos", uf: "SP", origin: "goiania" },
  { name: "Cunha", uf: "SP", origin: "goiania" },
  { name: "Diadema", uf: "SP", origin: "goiania" },
  { name: "Dumont", uf: "SP", origin: "goiania" },
  { name: "Elias Fausto", uf: "SP", origin: "goiania" },
  { name: "Embu das Artes", uf: "SP", origin: "goiania" },
  { name: "Embu-Guaçu", uf: "SP", origin: "goiania" },
  { name: "Ferraz de Vasconcelos", uf: "SP", origin: "goiania" },
  { name: "Franco da Rocha", uf: "SP", origin: "goiania" },
  { name: "Guararema", uf: "SP", origin: "goiania" },
  { name: "Guaratinguetá", uf: "SP", origin: "goiania" },
  { name: "Guarulhos", uf: "SP", origin: "goiania" },
  { name: "Hortolândia", uf: "SP", origin: "goiania" },
  { name: "Ibiúna", uf: "SP", origin: "goiania" },
  { name: "Igaratá", uf: "SP", origin: "goiania" },
  { name: "Indaiatuba", uf: "SP", origin: "goiania" },
  { name: "Iperó", uf: "SP", origin: "goiania" },
  { name: "Itapecerica da Serra", uf: "SP", origin: "goiania" },
  { name: "Itapetininga", uf: "SP", origin: "goiania" },
  { name: "Itapevi", uf: "SP", origin: "goiania" },
  { name: "Itaquaquecetuba", uf: "SP", origin: "goiania" },
  { name: "Itatiba", uf: "SP", origin: "goiania" },
  { name: "Itu", uf: "SP", origin: "goiania" },
  { name: "Itupeva", uf: "SP", origin: "goiania" },
  { name: "Jacareí", uf: "SP", origin: "goiania" },
  { name: "Jaguariúna", uf: "SP", origin: "goiania" },
  { name: "Jandira", uf: "SP", origin: "goiania" },
  { name: "Jardinópolis", uf: "SP", origin: "goiania" },
  { name: "Jarinu", uf: "SP", origin: "goiania" },
  { name: "Jundiaí", uf: "SP", origin: "goiania" },
  { name: "Lagoinha", uf: "SP", origin: "goiania" },
  { name: "Laranjal Paulista", uf: "SP", origin: "goiania" },
  { name: "Limeira", uf: "SP", origin: "goiania" },
  { name: "Lorena", uf: "SP", origin: "goiania" },
  { name: "Louveira", uf: "SP", origin: "goiania" },
  { name: "Mairinque", uf: "SP", origin: "goiania" },
  { name: "Mairiporã", uf: "SP", origin: "goiania" },
  { name: "Mauá", uf: "SP", origin: "goiania" },
  { name: "Mogi das Cruzes", uf: "SP", origin: "goiania" },
  { name: "Mococa", uf: "SP", origin: "goiania" },
  { name: "Monte Mor", uf: "SP", origin: "goiania" },
  { name: "Monteiro Lobato", uf: "SP", origin: "goiania" },
  { name: "Natividade da Serra", uf: "SP", origin: "goiania" },
  { name: "Nazaré Paulista", uf: "SP", origin: "goiania" },
  { name: "Nova Odessa", uf: "SP", origin: "goiania" },
  { name: "Orlândia", uf: "SP", origin: "goiania" },
  { name: "Osasco", uf: "SP", origin: "goiania" },
  { name: "Paraibuna", uf: "SP", origin: "goiania" },
  { name: "Paulínia", uf: "SP", origin: "goiania" },
  { name: "Piedade", uf: "SP", origin: "goiania" },
  { name: "Pilar do Sul", uf: "SP", origin: "goiania" },
  { name: "Pindamonhangaba", uf: "SP", origin: "goiania" },
  { name: "Piquete", uf: "SP", origin: "goiania" },
  { name: "Piracicaba", uf: "SP", origin: "goiania" },
  { name: "Pirapora do Bom Jesus", uf: "SP", origin: "goiania" },
  { name: "Poá", uf: "SP", origin: "goiania" },
  { name: "Pontal", uf: "SP", origin: "goiania" },
  { name: "Porto Feliz", uf: "SP", origin: "goiania" },
  { name: "Potim", uf: "SP", origin: "goiania" },
  { name: "Pradópolis", uf: "SP", origin: "goiania" },
  { name: "Queluz", uf: "SP", origin: "goiania" },
  { name: "Rancharia", uf: "SP", origin: "goiania" },
  { name: "Ribeirão Pires", uf: "SP", origin: "goiania" },
  { name: "Ribeirão Preto", uf: "SP", origin: "goiania" },
  { name: "Rio das Pedras", uf: "SP", origin: "goiania" },
  { name: "Rio Grande da Serra", uf: "SP", origin: "goiania" },
  { name: "Roseira", uf: "SP", origin: "goiania" },
  { name: "Salesópolis", uf: "SP", origin: "goiania" },
  { name: "Salto", uf: "SP", origin: "goiania" },
  { name: "Salto de Pirapora", uf: "SP", origin: "goiania" },
  { name: "Santa Bárbara d'Oeste", uf: "SP", origin: "goiania" },
  { name: "Santa Branca", uf: "SP", origin: "goiania" },
  { name: "Santana de Parnaíba", uf: "SP", origin: "goiania" },
  { name: "Santo André", uf: "SP", origin: "goiania" },
  { name: "São Bernardo do Campo", uf: "SP", origin: "goiania" },
];
